# Generated by Django 6.1 on 2026-08-16 18:05

import drops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=drops.models.generate_public_id, editable=False, max_length=16, unique=True)),
                ('content', models.TextField()),
                ('language', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('burn_after_reading', models.BooleanField(default=False)),
            ],
        ),
    ]
